AWSTemplateFormatVersion: '2010-09-09'
Description: Setup for Budget Alarms with Email Notifications

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Notification Settings"
        Parameters:
          - EmailAddress
          - PhoneNumber
      - Label:
          default: "Budget Settings"
        Parameters:
          - SoftLimit
          - HardLimit

Parameters:
  SoftLimit:
    Type: Number
    Default: 100
    Description: >
      Sets the soft limit for budget alerts in USD. This limit serves as a preliminary 
      warning threshold. When actual or forecasted monthly usage reaches this limit, 
      you will receive a notification. This alert allows for proactive budget management 
      and enables you to adjust your usage or budget before the hard limit is reached.
  HardLimit:
    Type: Number
    Default: 0
    Description: >
      Optional. Specifies the hard limit for budget alerts in USD. When this limit is reached, 
      the IAM policy of the ContentfulBedrockUser, which grants access to Bedrock services, 
      will be automatically removed. This action serves as a cost control measure, 
      preventing further usage of Bedrock services. To restore access, the budget limit 
      needs to be adjusted, and the IAM policy must be manually reattached.
  EmailAddress:
    Type: String
    Description: Email address to receive budget alerts.
  
  PhoneNumber:
    Type: String
    Default: ''
    Description: "Optional. Phone number for SMS alerts in E.164 format, e.g., +12065550100."

Conditions:
  CreateSMSNotification: !Not [!Equals [!Ref PhoneNumber, '']]
  CreateHardLimit: !Not [!Equals [!Ref HardLimit, 0]]
  CreateSMSAndHardLimit: !And
    - Condition: CreateSMSNotification
    - Condition: CreateHardLimit
  CreateEmailAndHardLimit: !And
    - Condition: CreateSMSNotification
    - Condition: CreateHardLimit

Resources:

  SoftLimitAlarmTopic:
    Type: 'AWS::SNS::Topic'

  HardLimitAlarmTopic:
    Type: 'AWS::SNS::Topic'
    Condition: CreateHardLimit

  EmailSubscriptionSoftLimit:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: email
      Endpoint: !Ref EmailAddress
      TopicArn: !Ref SoftLimitAlarmTopic

  EmailSubscriptionHardLimit:
    Type: 'AWS::SNS::Subscription'
    Condition: CreateEmailAndHardLimit
    Properties:
      Protocol: email
      Endpoint: !Ref EmailAddress
      TopicArn: !Ref HardLimitAlarmTopic

  SMSSubscriptionSoftLimit:
    Type: 'AWS::SNS::Subscription'
    Condition: CreateSMSNotification
    Properties:
      Protocol: sms
      Endpoint: !Ref PhoneNumber
      TopicArn: !Ref SoftLimitAlarmTopic

  SMSSubscriptionHardLimit:
    Type: 'AWS::SNS::Subscription'
    Condition: CreateSMSAndHardLimit
    Properties:
      Protocol: sms
      Endpoint: !Ref PhoneNumber
      TopicArn: !Ref HardLimitAlarmTopic

  SoftLimitBudget:
    Type: 'AWS::Budgets::Budget'
    Properties:
      Budget:
        BudgetLimit:
          Amount: !Ref SoftLimit
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 75
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref SoftLimitAlarmTopic

  HardLimitBudget:
    Type: 'AWS::Budgets::Budget'
    Condition: CreateHardLimit
    Properties:
      Budget:
        BudgetLimit:
          Amount: !Ref HardLimit
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref HardLimitAlarmTopic

Outputs:
  SoftLimitAlarmTopicArn:
    Description: "ARN of the Soft Limit Alarm SNS Topic"
    Value: !Ref SoftLimitAlarmTopic

  HardLimitAlarmTopicArn:
    Condition: CreateHardLimit
    Description: "ARN of the Hard Limit Alarm SNS Topic"
    Value: !Ref HardLimitAlarmTopic
